@startuml
skin rose

participant User 
entity frontend
entity backend
entity "Ad Server"
database Database

' Display form and submit question
User -> frontend : Access application
frontend -- User : Display question input form
User -> frontend : Submit question ("What should I do to..." / "What should I do if...")

' Backend processing & database query
frontend -> backend : Send question
backend -> backend : Standardize question text using NLP
backend -> Database : Query answer for standardized question

' Alternative flow for query outcome
alt answer found in databse 
	Database --> backend : Return answer
	backend --> frontend : Return answer
else Answer not found in database
	Database --> backend : No answer found
	backend -> Database : Save question for future review
	backend --> frontend : Return placeholder ("Hmm... Let me think about it. Ask me again in 24 hours.")
end

' Revenue generation flow
frontend -> "Ad Server" : Request new advertisement 
"Ad Server" --> frontend : Return advertisement

' Final presentation to user
frontend --> User : Display response alongside advertisement

@enduml
